allowBuilds:
  '@google/genai': true
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - '@sveltejs/kit'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - workerd
