// This was made for Selector.svelte
// The names need to stay in sync with the themes in $lib/app.css
//    unless another technique is discovered to dynamically load them.
export default [
	'light',
	'dark',
	'aqua',
	'autumn',
	'bumblebee',
	'business',
	'cmyk',
	'coffee',
	'corporate',
	'cupcake',
	'cyberpunk',
	'dim',
	'emerald',
	'fantasy',
	'forest',
	'garden',
	'lemonade',
	'lofi',
	'luxury',
	'night',
	'nord',
	'pastel',
	'reformation',
	'retro',
	'sunset',
	'synthwave',
	'valentine',
	'winter',
	'wireframe',
]
