/** @type { import('.').ContextArgumentMap } */
export const context_argument_map = new Map([
	['Noun', [
		'Verb',
		'Role',
		'Adposition',
		'Outer Noun',
		'Outer Adjective',
		'Outer Adverb',
	]],
	['Verb', [
		'Topic NP',
		'Polarity',
		'Agent',
		'Patient',
		'State',
		'Source',
		'Destination',
		'Instrument',
		'Beneficiary',
		'Addressee',
		'Predicate Adjective',
		'Propositional Agent',
		'Propositional Patient',
	]],
	['Adjective', [
		'Degree',
		'Verb',
		'Agent',
		'Modified Noun',
		'Modified Adjective',
		'Patient Noun',
		'Patient Clause',
		'Usage',
	]],
	['Adverb', [
		'Degree',
		'Verb',
		'Modified Noun',
		'Modified Adjective',
	]],
	['Adposition', [
		'Noun',
		'Verb',
		'Adjective',
		'Outer Noun',
		'Outer Adjective',
	]],
])
