# https://developers.cloudflare.com/workers/wrangler/configuration

[[d1_databases]]
binding = "DB_Ontology" # i.e. available in your Worker on env.DB
database_name = "Ontology.2024-01-30.3_0_9485"
database_id = "84506589-8c5f-4933-a3d6-329b64c89f7d"
