# https://developers.cloudflare.com/workers/wrangler/configuration

# https://developers.cloudflare.com/workers/wrangler/configuration/#custom-builds
[build]
command = "pnpm build"

[[d1_databases]]
binding = "DB_Ontology" # i.e. available in your Worker on env.DB
database_name = "Ontology.2024-03-12.3_0_9485"
database_id = "15085bb6-994e-4837-acc0-0623c74cf444"
