# https://developers.cloudflare.com/workers/wrangler/configuration

[[d1_databases]]
binding = "DB_Ontology" # i.e. available in a Worker on env.DB
database_name = "Ontology.2024-02-27.3_0_9485"
database_id = "0f9e4da1-db8e-45d5-a086-bee36dc396f4"