# https://developers.cloudflare.com/workers/wrangler/configuration

# https://developers.cloudflare.com/workers/wrangler/configuration/#inheritable-keys
name = "complex_terms_sync"
main = "index.js"
compatibility_date = "2024-02-28"
workers_dev = false

# https://developers.cloudflare.com/workers/configuration/cron-triggers
[triggers]
crons = ["0 */12 * * *"]

[[d1_databases]]
binding = "DB_Ontology" # i.e. available in a Worker on env.DB
database_name = "Ontology.9489.2024-06-27"
database_id = "b49b6a69-9f69-4b85-9b36-593cd28e2440"